services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  logger:
    build: .
    command: ["python", "logger.py"]
    environment:
      - SERVICE_NAME=telemetry-logger
    restart: unless-stopped